name: "Build"
on:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
  push:
    branches:
      - main
      - develop
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'

jobs:
  pr-build:
    if: >
      github.event_name == 'pull_request' && !github.event.pull_request.draft && (
        github.event.action == 'opened' ||
        github.event.action == 'reopened' ||
        github.event.action == 'synchronize' 
      )
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v3.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
          
      - name: Test Maven settings in PR
        run: mvn help:effective-settings
        
      - name: "Setting up Artifactory authentication"
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: '[{"id": "central", "username": "${env.ARTIFACTORY_USER}", "password": "${env.ARTIFACTORY_TOKEN}"}]'
          githubServer: false
          
      - name: Build with Maven
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: mvn -X package

  build:
    if: github.repository == 'pixee-testuser-jupiter/WebGoat' && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: "Branch build"
    steps:
        - uses: actions/checkout@v3
        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
              distribution: 'temurin'
              java-version: 17
              architecture: x64
        - name: Cache Maven packages
          uses: actions/cache@v3.0.2
          with:
              path: ~/.m2
              key: ubuntu-latest-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ubuntu-latest-m2-
        - name: Test Maven settings in Build
          run: mvn help:effective-settings

        - name: "Setting up Artifactory authentication"
          uses: s4u/maven-settings-action@v2.6.0
          with:
            servers: '[{"id": "central", "username": "${env.ARTIFACTORY_USER}", "password": "${env.ARTIFACTORY_TOKEN}"}]'
            githubServer: false
            
        - name: Test with Maven
          run: mvn -X verify
